language: generic

dist: trusty
sudo: required

env:
  global:
    - DEPENDENCY_DIR="${TRAVIS_BUILD_DIR}/dependencies"

cache:
  directories:
    - ${DEPENDENCY_DIR}


matrix:
    include:
    - env: CXX=g++-7 CC=gcc-7
      addons:
        apt:
          packages:
            - g++-7
          sources: &sources
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty-5.0
    - env: CXX=g++-6 CC=gcc-6
      addons:
        apt:
          packages:
            - g++-6
          sources: *sources
    - env: CXX=clang++-5.0 CC=clang-5.0
      addons:
        apt:
          packages:
            - clang-5.0
          sources: *sources
    - env: CXX=clang++-4.0 CC=clang-4.0
      addons:
        apt:
          packages:
            - clang-4.0
          sources: *sources


install:
    - script/ci_install.sh
    - script/ci_travis_clang_workaround.sh
    - script/ci_install_deps.sh

script:
    - script/ci_build.sh

