//----------------------------------------------------------------------
// WARNING: This file was generated by config2cpp-nocheck. Do not edit.
//
// Description: a class providing access to an embedded
//              configuration string.
//----------------------------------------------------------------------

#pragma once

#include "danek/Configuration.h"

namespace danek
{
    class DefaultSecurity
    {
    public:

        DefaultSecurity();
        DefaultSecurity(const DefaultSecurity&) = delete;


        const char* getString() const
        {
            return m_str.c_str();
        }


        DefaultSecurity& operator=(const DefaultSecurity&) = delete;

    private:

        danek::StringBuffer m_str;
    };

} // namespace danek
