//----------------------------------------------------------------------
// WARNING: This file was generated by config2cpp-nocheck. Do not edit.
//
// Description: a class providing access to an embedded
//              configuration string.
//----------------------------------------------------------------------

#pragma once

#include <string>

namespace danek
{
    class DefaultSecurity
    {
    public:

        DefaultSecurity();


        const char* getString() const
        {
            return m_str.c_str();
        }


    private:

        const std::string m_str;
    };

} // namespace danek
