//----------------------------------------------------------------------
// WARNING: This file was generated by config2cpp-nocheck. Do not edit.
//
// Description: a class providing access to an embedded
//              configuration string.
//----------------------------------------------------------------------

#pragma once

#include "danek/Configuration.h"

namespace danek
{
    class DefaultSecurity
    {
    public:
        //--------
        // Constructor and destructor.
        //--------
        DefaultSecurity();
        ~DefaultSecurity();

        //--------
        // Get the configuration string
        //--------
        const char* getString()
        {
            return m_str.c_str();
        }

    private:
        //--------
        // Variables
        //--------
        danek::StringBuffer m_str;

        //--------
        // The following are not implemented
        //--------
        DefaultSecurity& operator=(const DefaultSecurity&);
        DefaultSecurity(const DefaultSecurity&);
    };

} // namespace danek
