name: ci

on: [push, pull_request]

jobs:
  build_linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - gcc:13
          - gcc:12
          - gcc:11
          - gcc:10
          - gcc:9
          - clang:16
          - clang:15
          - clang:14
          - clang:13
          - clang:12
    container:
      image: "registry.gitlab.com/offa/docker-images/${{ matrix.compiler }}"
    name: "${{ matrix.compiler }}"
    steps:
      - uses: actions/checkout@main
      - name: Build
        run: script/ci_build.sh
